services:
  - type: web
    name: healthcare-backend
    env: docker
    rootDir: backend
    plan: starter
    autoDeploy: true
    healthCheckPath: /files/
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION
        value: healthcare_docs
      - key: GEMINI_API_KEY
        sync: false
      - key: ENTERTAINMENT_API_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract

  - type: web
    name: healthcare-frontend
    env: node
    rootDir: frontend
    plan: starter
    autoDeploy: true
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm run start
    envVars:
      # Set this manually in the frontend service after the backend is created:
      # https://<your-backend-service-host>.onrender.com
      - key: NEXT_PUBLIC_API_URL
        sync: false